## K-Means Clustering


Basic logic:
Repeat until convergence:
1. Assign points to closest centroid 
2. Recalculate centroids based on new assignments

APPROACH 1: Set each point to a centroid at random.

APPROACH 2: Set centroids at random and assign points to closest centroid

Normalization typically helps, as it gives equal importance to variables.

Quality measure = sum of dissimilarity from points to centroids
Distortion function for k-means:

$$ J(c,\mu) = \sum_{i=1}^{m} ||x^{(i)}-\mu_{c^{(i)}}||^2 $$ 


where $c^{(i)}$ is cluster assignment for point $i$ and $\mu_j$	is centroid for cluster $j$

This is a non-convex function, so not guaranteed to converge to global minimum



In [2]:
# Code below is from scikit-learn documentation

import sklearn
from sklearn.cluster import KMeans
import numpy as np
X = np.array([[1, 2], [1, 4], [1, 0],[4, 2], [4, 4], [4, 0]])
X

array([[1, 2],
       [1, 4],
       [1, 0],
       [4, 2],
       [4, 4],
       [4, 0]])

In [3]:
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
kmeans.labels_

array([0, 0, 0, 1, 1, 1], dtype=int32)

In [4]:
kmeans.predict([[0, 0], [4, 4]])

array([0, 1], dtype=int32)

In [5]:
kmeans.cluster_centers_

array([[ 1.,  2.],
       [ 4.,  2.]])